name: Create A File
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main

jobs:
  buildOtel:
    name: Build otelcol using builder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -al build/
      - uses: rogercoll/otelcol-builder-action@main
        with:
          local_manifest: './distributions/otelcol/manifest.yaml'
          local_output_path: './build'
      - run: ls -al build/
