name: Create A File
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main

jobs:
  createFile:
    name: Create A File
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rogercoll/otelcol-builder-action@main
        with:
          manifest: './distributions/otelcol/manifest.yaml'
          outputpath: './build'
      - run: ls -al build/
