name: Release from a working version
on:
  workflow_dispatch:
    inputs:
      working_version:
        description: 'Tag to backup assets and docker image from'
        required: true
      new_version:
        description: 'New release version'
        required: true

env:
  DOCKER_HUB_ID: ${{ secrets.DOCKER_HUB_ID }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Backup version ${{ github.event.inputs.working_version }}!\n"
          echo "New release version ${{ github.event.inputs.new_version }}!"
          # publish-docker-iamges:
    #    runs-on: ubuntu-20.04
    #    steps:
    #  - name: Login to DockerHub
    #    uses: docker/login-action@v1
    #    with:
    #      username: ${{ env.DOCKER_HUB_ID }}
    #      password: ${{ env.DOCKER_HUB_PASSWORD }}
    #  - name: Setup crane
    #    uses: imjasonh/setup-crane@v0.1
    #  - name: Publish new latest image from tag
    #    run: crane tag coll97/s3sidecar:${{ github.event.inputs.working_version }} ${{ github.event.inputs.new_version }} 
  publish-old-assets:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: robinraju/release-downloader@v1.3
        with: 
          repository: rogercoll/githubTests
          tag: ${{ github.event.inputs.working_version }}
          # The name of the file to download.
          # Use this field only to specify filenames other than tarball or zipball, if any.
          # Use '*' to download all assets
          fileName: "*"
      - name: Rename files
        run: |
          ls -al
          rename 's/${{ github.event.inputs.working_version }}/${{ github.event.inputs.new_version }}/g' *
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: | 
            Release-amd64-${{ github.event.inputs.new_version }}.txt
            Release-arm64-${{ github.event.inputs.new_version }}.txt
