name: Release from a working version
on:
  workflow_dispatch:
    inputs:
      working_version:
        description: 'Tag to backup assets and docker image from'
        required: true
      new_version:
        description: 'New release version'
        required: false

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Backup version ${{ github.event.inputs.working_version }}!\n"
          echo "New release version ${{ github.event.inputs.working_version }}!"
