name: Release from a working version
on:
  workflow_dispatch:
    inputs:
      working_version:
        description: 'Tag to backup assets and docker image from'
        required: true
      new_version:
        description: 'New release version'
        required: true

env:
  DOCKER_HUB_ID: ${{ secrets.DOCKER_HUB_ID }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Backup version ${{ github.event.inputs.working_version }}!\n"
          echo "New release version ${{ github.event.inputs.new_version }}!"
          # publish-docker-iamges:
    #    runs-on: ubuntu-20.04
    #    steps:
    #  - name: Login to DockerHub
    #    uses: docker/login-action@v1
    #    with:
    #      username: ${{ env.DOCKER_HUB_ID }}
    #      password: ${{ env.DOCKER_HUB_PASSWORD }}
    #  - name: Setup crane
    #    uses: imjasonh/setup-crane@v0.1
    #  - name: Publish new latest image from tag
    #    run: crane tag coll97/s3sidecar:${{ github.event.inputs.working_version }} ${{ github.event.inputs.new_version }} 
  publish-old-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: List Releases
        run: | 
          gh release list --repo rogercoll/githubTests
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: download assets 
        run:  |
          mkdir dist
          gh release download ${{ github.event.inputs.working_version }} --repo rogercoll/githubTests -D ./dist
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Rename files
        run: |
          ls -al ./dist
          find ./dist -name '*${{ github.event.inputs.working_version }}*' -exec bash -c ' mv $0 ${0/${{ github.event.inputs.working_version }}/${{ github.event.inputs.new_version }}}' {} \;
          ls -al ./dist
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: | 
            Release-amd64-${{ github.event.inputs.new_version }}.txt
            Release-arm64-${{ github.event.inputs.new_version }}.txt
