name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        required: false
        default: '0.0.1-rc'
  schedule:
    - cron: "5 0 * 8 *"

jobs:
  # Note: Snyk SaaS is already configured for this repository, which does not need a workflow to run
  trivy:
    uses: ./.github/workflows/security_component.yml
    secrets:
      slack_webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      tag: "${{ inputs.tag }}"
