name: 🕵 Testing
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to scan'
        required: true
jobs:
  parse-tag:
    name: Transform semantic version tag
    runs-on: ubuntu-20.04
    outputs:
      tag: ${{ steps.set_outputs.outputs.test-result }}
    steps:
      - name: Print the value of the release tag
        run: echo "${{ github.event.inputs.tag }}"
      - name: Set the value of the release tag
        run: echo "tag=$(echo ${{ github.event.inputs.tag }} | cut -c2-)" >> $GITHUB_ENV
      - name: Print new value of env variable
        run: echo "${{ env.tag }}"
  do-release:
    needs: [parse-tag]
    name: Print previously set env
    runs-on: ubuntu-20.04
    steps:
      - name: Print the value of the release tag
        run: echo "${{ env.tag }}"
