name: 🕵 Testing
on:
  push:
    branches:
      - main
jobs:
  windows-date:
    name: Get date RFC3339 format
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run bash script
        run: bash.exe ./say_hello.sh
      - name: Print date
        run: date
      - name: Print UTC date
        run: date -u
      - name: Print date in RCF3339 format using bash
        shell: bash
        run: date -u +"%Y-%m-%dT%H:%M:%SZ"
      - name: Print date in RCF3339 format using pwsh
        shell: pwsh
        run: date -u +"%Y-%m-%dT%H:%M:%SZ"
      - name: Set the value of the registered date
        run: echo buildDate=$(date -u +"%Y-%m-%dT%H:%M:%SZ") >> $GITHUB_ENV
        shell: bash
      - name: Print new value of env variable
        run: echo "${{ env.buildDate }}"
